version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: imagedup
    main: ./cmd/nsquared/main.go
    binary: nsquared
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

  - id: uniqdirs
    main: ./cmd/uniqdirs/main.go
    binary: uniqdirs
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

  - id: verify
    main: ./cmd/verify/main.go
    binary: verify
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

release:
  github:
    owner: kmulvey
    name: imagedup
  # Whether to remove existing draft releases with the same name before creating
  replace_existing_draft: true
  # Whether to remove an artifact that already exists.
  replace_existing_artifacts: true

archives:
  - id: dist
    builds:
      - nsquared
      - uniqdirs
      - verify
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"


nfpms:
  # note that this is an array of nfpm configs
  - # ID of the nfpm config, must be unique.
    id: imagedup

    package_name: imagedup

    builds:
      - nsquared
      - uniqdirs
      - verify

    # Your app's vendor.
    vendor: Kevin Mulvey

    # Your app's homepage.
    homepage: https://github.com/kmulvey/imagedup

    # Your app's maintainer (probably you).
    maintainer: Drummer <drum-roll@example.com>

    # Your app's description.
    description: |-
       Find similar images in large image libraries with perceptual hashing 

    # Your app's license.
    license: MIT

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

    provides:
      - nsquared
      - uniqdirs
      - verify

    # Path that the binaries should be installed.
    # Default: '/usr/bin'
    bindir: /usr/bin

    # Custom configuration applied only to the RPM packager.
    rpm:
      group: root
      compression: lzma
      # The package is signed if a key_file is set
      #signature:
      # PGP secret key file path (can also be ASCII-armored).
      # The passphrase is taken from the environment variable
      # `$NFPM_ID_RPM_PASSPHRASE` with a fallback to `$NFPM_ID_PASSPHRASE`,
      # where ID is the id of the current nfpm config.
      # The id will be transformed to uppercase.
      # E.g. If your nfpm id is 'default' then the rpm-specific passphrase
      # should be set as `$NFPM_DEFAULT_RPM_PASSPHRASE`
      #
      # Templates: allowed
      #key_file: "/home/kmulvey/keys/sec.gpg"
