{
 "title": "Imagedup",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Percent Complete",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(imagedup_comparisons_completed/imagedup_total_comparisons)*100"
    }
   ]
  },
  {
   "title": "Diff Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(imagedup_pair_total[5m])", "legendFormat": "Diff/s" }
   ]
  },
  {
   "title": "Images in Cache",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imagedup_image_cache_num_images"
    }
   ]
  },
  {
   "title": "Diff Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "imagedup_diff_time_nano" }
   ]
  },
  {
   "title": "Image Cache Hits/Miss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(imagedup_image_hash_cache_hits[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(imagedup_image_hash_cache_misses[5m])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "imagedup_gc_time_nano" }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}"
    }
   ]
  }
 ]
}