name: ImageDup

on: push

jobs:
  build:
    name: ImageDup build
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      
      - name: Build & Test
        run: |
          go mod tidy
          go test -v -race -count 1 ./...
          go build -v -ldflags="-s -w" ./...

  release:
    name: ImageDup release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --config .goreleaser.yaml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

